// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAgency_BookingSystem.Infrastructure.Persistence;

#nullable disable

namespace WebAgency_BookingSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingSystemDbContext))]
    [Migration("20260619095329_AddGdprConsentVersion")]
    partial class AddGdprConsentVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAnonymized")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_anonymized");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_tenant_id_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<TimeOnly>("BookingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("booking_time");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid>("CancellationToken")
                        .HasColumnType("uuid")
                        .HasColumnName("cancellation_token");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text")
                        .HasColumnName("customer_notes");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_phone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("GdprConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("gdpr_consent");

                    b.Property<DateTimeOffset>("GdprConsentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gdpr_consent_at");

                    b.Property<string>("GdprConsentVersion")
                        .HasColumnType("text")
                        .HasColumnName("gdpr_consent_version");

                    b.Property<DateTimeOffset?>("NoShowMarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("no_show_marked_at");

                    b.Property<decimal?>("PriceAtBooking")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_booking");

                    b.Property<DateTimeOffset?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_sent_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CancellationToken")
                        .HasDatabaseName("ix_bookings_cancellation_token");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_bookings_service_id");

                    b.HasIndex("StaffId", "BookingDate")
                        .HasDatabaseName("ix_bookings_staff_id_booking_date");

                    b.HasIndex("TenantId", "BookingDate")
                        .HasDatabaseName("ix_bookings_tenant_id_booking_date");

                    b.HasIndex("Status", "ReminderSentAt", "BookingDate")
                        .HasDatabaseName("ix_bookings_status_reminder_sent_at_booking_date");

                    b.HasIndex("TenantId", "ServiceId", "BookingDate", "Status")
                        .HasDatabaseName("ix_bookings_tenant_id_service_id_booking_date_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.BookingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal?>("PriceAtBooking")
                        .HasColumnType("numeric")
                        .HasColumnName("price_at_booking");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_items");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_items_booking_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_booking_items_service_id");

                    b.ToTable("booking_items", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.OutboxEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("to_email");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_email_tenant_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_email_status_next_attempt_at");

                    b.ToTable("outbox_email", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.PlatformAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_access_count");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platform_admin");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_admin_email");

                    b.ToTable("platform_admin", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<bool>("BufferEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("buffer_enabled");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_minutes");

                    b.Property<string>("BufferPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("buffer_position");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("ParallelSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("parallel_slots");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_services_tenant_id");

                    b.HasIndex("TenantId", "Active")
                        .HasDatabaseName("ix_services_tenant_id_active");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialization");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_staff_tenant_id");

                    b.HasIndex("TenantId", "Active")
                        .HasDatabaseName("ix_staff_tenant_id_active");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.StaffBusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("BreakEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_end");

                    b.Property<TimeOnly?>("BreakStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_start");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_business_hours");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_staff_business_hours_tenant_id");

                    b.HasIndex("StaffId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_business_hours_staff_id_day_of_week");

                    b.ToTable("staff_business_hours", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.StaffService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("PriceOverride")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_override");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_services");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_staff_services_service_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_staff_services_tenant_id");

                    b.HasIndex("StaffId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_services_staff_id_service_id");

                    b.ToTable("staff_services", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.StaffTimeOff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff_time_off");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_staff_time_off_tenant_id");

                    b.HasIndex("StaffId", "DateFrom", "DateTo")
                        .HasDatabaseName("ix_staff_time_off_staff_id_date_from_date_to");

                    b.ToTable("staff_time_off", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MinAdvanceHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("min_advance_hours");

                    b.Property<int>("MinCancellationHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("min_cancellation_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NotificationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("email")
                        .HasColumnName("notification_method");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_email");

                    b.Property<int>("ReminderHoursBefore")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_hours_before");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("site_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<bool>("StaffChoiceEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("staff_choice_enabled");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Rome")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VisibleDaysAhead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("visible_days_ahead");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.TenantApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_api_keys_key_hash");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_api_keys_tenant_id");

                    b.ToTable("tenant_api_keys", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.TenantBusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("BreakEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_end");

                    b.Property<TimeOnly?>("BreakStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_start");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("close_time");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_open");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("open_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_business_hours");

                    b.HasIndex("TenantId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_business_hours_tenant_id_day_of_week");

                    b.ToTable("tenant_business_hours", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.TenantSpecialClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_special_closures");

                    b.HasIndex("TenantId", "DateFrom", "DateTo")
                        .HasDatabaseName("ix_tenant_special_closures_tenant_id_date_from_date_to");

                    b.ToTable("tenant_special_closures", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_access_count");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.UserSecurityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_security_token");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_user_security_token_token_hash");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_user_security_token_user_id_purpose");

                    b.ToTable("user_security_token", (string)null);
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Booking", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_services_service_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Staff", "Staff")
                        .WithMany("Bookings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bookings_staff_staff_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Bookings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_tenants_tenant_id");

                    b.Navigation("Service");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.BookingItem", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Booking", "Booking")
                        .WithMany("Items")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_items_bookings_booking_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_items_services_service_id");

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.OutboxEmail", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_email_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Service", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Services")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Staff", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Staff")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.StaffBusinessHours", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Staff", "Staff")
                        .WithMany("BusinessHours")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_business_hours_staff_staff_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_business_hours_tenants_tenant_id");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.StaffService", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Service", "Service")
                        .WithMany("StaffServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_services_services_service_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Staff", "Staff")
                        .WithMany("StaffServices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_services_staff_staff_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_services_tenants_tenant_id");

                    b.Navigation("Service");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.StaffTimeOff", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_time_off_staff_staff_id");

                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_time_off_tenants_tenant_id");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.TenantApiKey", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_api_keys_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.TenantBusinessHours", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("BusinessHours")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_business_hours_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.TenantSpecialClosure", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("SpecialClosures")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_special_closures_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.User", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.UserSecurityToken", b =>
                {
                    b.HasOne("WebAgency_BookingSystem.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_security_token_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Booking", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("StaffServices");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Staff", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BusinessHours");

                    b.Navigation("StaffServices");
                });

            modelBuilder.Entity("WebAgency_BookingSystem.Core.Entities.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Bookings");

                    b.Navigation("BusinessHours");

                    b.Navigation("Services");

                    b.Navigation("SpecialClosures");

                    b.Navigation("Staff");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
